version: '3.7'

services:
  react-app:
    build: 
      context: .
      args:
        REACT_APP_API_PORT: ${REACT_APP_API_PORT}
        REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    container_name: shop-for-me-frontend
    ports:
      - "3000:80"
    restart: always