version: "3.8"
services:
  arduino-uploader:
    build: .
    container_name: arduino-uploader
    volumes:
      - ./iot/Bench_Test:/app
    devices:
      - "/dev/serial/by-id:/dev/serial/by-id" # Montage des ports COM
    environment:
      - PYTHONUNBUFFERED=1
