<<<<<<< HEAD
# 📌 Test for Flutter Part
=======
>>>>>>> 81-front
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

<<<<<<< HEAD
=======
      # 📌 Checking for Flutter (mobile repository)
>>>>>>> 81-front
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

<<<<<<< HEAD
      - name: Build & Test
=======
      - name: Build & Test (Flutter)
>>>>>>> 81-front
        run: |
          flutter pub get
          flutter build apk --debug
          flutter test --coverage || echo "Tests failed, but continuing..."
        working-directory: mobile

<<<<<<< HEAD
=======
      # 📌 Checking for NodeJS (backend repository)
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend dependencies
        run: |
          cd backend
          npm install

      - name: Run tests (Backend)
        run: |
          cd backend
          npm run test -- --coverage
        working-directory: backend

      - name: Lint Backend code
        run: |
          cd backend
          npx eslint 'src/**/*.ts' --fix


      # 📌 SonarCloud analysis
>>>>>>> 81-front
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.projectKey=shopforme
            --define sonar.organization=shopforme
<<<<<<< HEAD
            --define sonar.projectBaseDir=./mobile
            --define sonar.javascript.lcov.reportPaths=coverage/lcov.info
            --define sonar.c.file.suffixes=-
            --define sonar.cpp.file.suffixes=-
            --define sonar.objc.file.suffixes=-

=======
            --define sonar.sources=mobile,backend
            --define sonar.javascript.lcov.reportPaths=coverage/lcov.info
            --define sonar.typescript.tsconfigPath=backend/tsconfig.json
            --define sonar.c.file.suffixes=-
            --define sonar.cpp.file.suffixes=-
            --define sonar.objc.file.suffixes=-
>>>>>>> 81-front
