# 📌 Test for Flutter Part
name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary for a good analysis

      # 📌 Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.1' 

      # 📌 Installing dependencies and building the project
      - name: Build & Test
        run: |
          flutter pub get
          flutter build apk --debug  # Compile the project in debug mode
          flutter test --coverage  # Runs the tests and generates the coverage file
        working-directory: mobile

      # 📌 Scanning with SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.coverageReportPaths=coverage/lcov.info
